server:
  port: 8080

spring:
  application:
    name: calendar
  jackson:
    time-zone: Europe/Madrid

logging:
  file:
    path: ./target/
    name: ${spring.application.name}
    level:
      com.julian: DEBUG
      org.springframework.boot: INFO
      org.springframework.web: INFO

springdoc:
   swagger-ui:
     operationsSorter: alpha
     tagsSorter: alpha          
# =========================
# GOOGLE CONFIG (CLAVE)
# =========================
google:
   credentials:
     path: ${GOOGLE_CREDENTIALS:src/main/resources/credentials.json}
     tokens:
         path: ${GOOGLE_TOKENS:./tokens}